# Bài tập 2 - Thư viện NumPy và pandas

*(Thống kê máy tính và ứng dụng - ĐTTX Kì 1 2023-2024)*

MSSV: 20810229

Họ và tên: Mai Đình Thái Sơn

Python 3.9.6

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Câu 1 (1.5 đ)

Tạo `arr` là một tensor 3D kích thước 2x4x5, gồm các số chia đều từ 0 đến 1.

1. Đổi dạng `arr` thành vector

1. Đổi dạng `arr` thành ma trận có 2 dòng

1. Đổi dạng `arr` thành ma trận có 4 cột

1. Đổi dạng `arr` thành 5x4x2

1. Thêm một chiều cho `arr` thành tensor 4D 1x2x4x5

1. Thêm một chiều cho `arr` thành tensor 4D 2x4x5x1

In [2]:
arr = np.linspace(0, 1, 40).reshape(2, 4, 5)
arr

array([[[0.        , 0.02564103, 0.05128205, 0.07692308, 0.1025641 ],
        [0.12820513, 0.15384615, 0.17948718, 0.20512821, 0.23076923],
        [0.25641026, 0.28205128, 0.30769231, 0.33333333, 0.35897436],
        [0.38461538, 0.41025641, 0.43589744, 0.46153846, 0.48717949]],

       [[0.51282051, 0.53846154, 0.56410256, 0.58974359, 0.61538462],
        [0.64102564, 0.66666667, 0.69230769, 0.71794872, 0.74358974],
        [0.76923077, 0.79487179, 0.82051282, 0.84615385, 0.87179487],
        [0.8974359 , 0.92307692, 0.94871795, 0.97435897, 1.        ]]])

In [3]:
#1. vecto
arr.reshape(-1)

array([0.        , 0.02564103, 0.05128205, 0.07692308, 0.1025641 ,
       0.12820513, 0.15384615, 0.17948718, 0.20512821, 0.23076923,
       0.25641026, 0.28205128, 0.30769231, 0.33333333, 0.35897436,
       0.38461538, 0.41025641, 0.43589744, 0.46153846, 0.48717949,
       0.51282051, 0.53846154, 0.56410256, 0.58974359, 0.61538462,
       0.64102564, 0.66666667, 0.69230769, 0.71794872, 0.74358974,
       0.76923077, 0.79487179, 0.82051282, 0.84615385, 0.87179487,
       0.8974359 , 0.92307692, 0.94871795, 0.97435897, 1.        ])

In [4]:
#2. ma trận có 2 dòng
arr.reshape(2,-1)
arr

array([[[0.        , 0.02564103, 0.05128205, 0.07692308, 0.1025641 ],
        [0.12820513, 0.15384615, 0.17948718, 0.20512821, 0.23076923],
        [0.25641026, 0.28205128, 0.30769231, 0.33333333, 0.35897436],
        [0.38461538, 0.41025641, 0.43589744, 0.46153846, 0.48717949]],

       [[0.51282051, 0.53846154, 0.56410256, 0.58974359, 0.61538462],
        [0.64102564, 0.66666667, 0.69230769, 0.71794872, 0.74358974],
        [0.76923077, 0.79487179, 0.82051282, 0.84615385, 0.87179487],
        [0.8974359 , 0.92307692, 0.94871795, 0.97435897, 1.        ]]])

In [5]:
#3. ma trận 4 cột
arr.reshape(-1,4)

array([[0.        , 0.02564103, 0.05128205, 0.07692308],
       [0.1025641 , 0.12820513, 0.15384615, 0.17948718],
       [0.20512821, 0.23076923, 0.25641026, 0.28205128],
       [0.30769231, 0.33333333, 0.35897436, 0.38461538],
       [0.41025641, 0.43589744, 0.46153846, 0.48717949],
       [0.51282051, 0.53846154, 0.56410256, 0.58974359],
       [0.61538462, 0.64102564, 0.66666667, 0.69230769],
       [0.71794872, 0.74358974, 0.76923077, 0.79487179],
       [0.82051282, 0.84615385, 0.87179487, 0.8974359 ],
       [0.92307692, 0.94871795, 0.97435897, 1.        ]])

In [6]:
#4. Dạng 5x4x2
arr.reshape(5,4,2)

array([[[0.        , 0.02564103],
        [0.05128205, 0.07692308],
        [0.1025641 , 0.12820513],
        [0.15384615, 0.17948718]],

       [[0.20512821, 0.23076923],
        [0.25641026, 0.28205128],
        [0.30769231, 0.33333333],
        [0.35897436, 0.38461538]],

       [[0.41025641, 0.43589744],
        [0.46153846, 0.48717949],
        [0.51282051, 0.53846154],
        [0.56410256, 0.58974359]],

       [[0.61538462, 0.64102564],
        [0.66666667, 0.69230769],
        [0.71794872, 0.74358974],
        [0.76923077, 0.79487179]],

       [[0.82051282, 0.84615385],
        [0.87179487, 0.8974359 ],
        [0.92307692, 0.94871795],
        [0.97435897, 1.        ]]])

In [7]:
#5. Dạng 1x2x4x5
arr.reshape(1,2,4,5)

array([[[[0.        , 0.02564103, 0.05128205, 0.07692308, 0.1025641 ],
         [0.12820513, 0.15384615, 0.17948718, 0.20512821, 0.23076923],
         [0.25641026, 0.28205128, 0.30769231, 0.33333333, 0.35897436],
         [0.38461538, 0.41025641, 0.43589744, 0.46153846, 0.48717949]],

        [[0.51282051, 0.53846154, 0.56410256, 0.58974359, 0.61538462],
         [0.64102564, 0.66666667, 0.69230769, 0.71794872, 0.74358974],
         [0.76923077, 0.79487179, 0.82051282, 0.84615385, 0.87179487],
         [0.8974359 , 0.92307692, 0.94871795, 0.97435897, 1.        ]]]])

In [8]:
#6. Dạng 2x4x5x1
arr.reshape(2,4,5,1)

array([[[[0.        ],
         [0.02564103],
         [0.05128205],
         [0.07692308],
         [0.1025641 ]],

        [[0.12820513],
         [0.15384615],
         [0.17948718],
         [0.20512821],
         [0.23076923]],

        [[0.25641026],
         [0.28205128],
         [0.30769231],
         [0.33333333],
         [0.35897436]],

        [[0.38461538],
         [0.41025641],
         [0.43589744],
         [0.46153846],
         [0.48717949]]],


       [[[0.51282051],
         [0.53846154],
         [0.56410256],
         [0.58974359],
         [0.61538462]],

        [[0.64102564],
         [0.66666667],
         [0.69230769],
         [0.71794872],
         [0.74358974]],

        [[0.76923077],
         [0.79487179],
         [0.82051282],
         [0.84615385],
         [0.87179487]],

        [[0.8974359 ],
         [0.92307692],
         [0.94871795],
         [0.97435897],
         [1.        ]]]])

## Câu 2 (1.5 đ)

Tạo `mat` là một ma trận kích thước 4x4 gồm các số nguyên với phần tử ở dòng $i$, cột $j$ là $i \times j$ (chỉ số dòng, cột tính từ 1).

1. Xuất ra dòng 1 của `mat`

1. Xuất ra cột 2 của `mat`

1. Xuất ra phần tử ở dòng cuối, cột cuối của `mat`

1. Xuất ra nửa trái của `mat`

1. Đặt tất cả các phần tử dòng cuối của `mat` là 0

1. Đặt tất cả các phần tử trên đường chéo chính của `mat` là 1

1. Tách `mat` theo chiều dọc thành 2 ma trận con lần lượt gồm 3 cột và 1 cột

1. Tách `mat` theo chiều ngang thành 2 ma trận con 2 dòng

In [9]:
mat = np.array([[i*j for j in range(1,5)] for i in range(1,5)])
mat

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [10]:
#1. Dòng 1 của mat
mat[1,:]

array([2, 4, 6, 8])

In [11]:
#2. Cột 2 của mat
mat[:,2]

array([ 3,  6,  9, 12])

In [12]:
#3 Dòng cuối cột cuối của mat
print(f'Dòng cuối :\n {mat[-1:,:]}')
print(f'Cột cuối :\n {mat[:,-1:]}')

Dòng cuối :
 [[ 4  8 12 16]]
Cột cuối :
 [[ 4]
 [ 8]
 [12]
 [16]]


In [13]:
#4 Xuất ra nửa trái của mat
left, right= np.hsplit(mat,[2])
left

array([[1, 2],
       [2, 4],
       [3, 6],
       [4, 8]])

## Câu 3 (2.5 đ)

1. Tìm hiểu bộ dữ liệu `Auto MPG Data Set` (https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

1. Download tập tin dữ liệu `auto-mpg.data` (https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data)

1. Nạp dữ liệu vào `DataFrame` tên là `auto_mpg` và kiểm tra thông tin của bảng dữ liệu nạp được

1. Lưu ý là bộ dữ liệu này có ô bị thiếu (đánh dấu bằng dấu ?), nạp lại dữ liệu cho đúng và kiểm tra lại thông tin của bảng dữ liệu

1. Kiểm tra có bao nhiêu ô NA, bao nhiêu dòng có chứa NA, bao nhiêu cột có chứa NA

1. Tìm chiến lược xử lý NA phù hợp (xóa các dòng chứa NA hay xóa các cột chứa NA hay điền giá trị cho NA với các chiến lược khác nhau)

1. Trích ra các dòng dữ liệu cho xe audi (cột car name)

1. Tính trung bình mpg các xe audi đã trích ở trên

1. Tương tự cho các xe ford có model year trước năm 1979

In [14]:
#.3 Nạp dữ liệu
auto_names = ["mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration","model_year","origin","car_name"]
auto_mpg = pd.read_csv('auto-mpg.data', delim_whitespace=True, skiprows = 0,names=auto_names)
auto_mpg

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0      130.0  3504.0          12.0   
1    15.0          8         350.0      165.0  3693.0          11.5   
2    18.0          8         318.0      150.0  3436.0          11.0   
3    16.0          8         304.0      150.0  3433.0          12.0   
4    17.0          8         302.0      140.0  3449.0          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0      86.00  2790.0          15.6   
394  44.0          4          97.0      52.00  2130.0          24.6   
395  32.0          4         135.0      84.00  2295.0          11.6   
396  28.0          4         120.0      79.00  2625.0          18.6   
397  31.0          4         119.0      82.00  2720.0          19.4   

     model_year  origin                   car_name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [15]:
#4. Kiểm tra lại thông tin của bảng dữ liệu
auto_mpg.isin(['?']).any()


mpg             False
cylinders       False
displacement    False
horsepower       True
weight          False
acceleration    False
model_year      False
origin          False
car_name        False
dtype: bool

In [16]:
# Thấy cột horsepower có dấu '?'. Lấy danh sách xe có horsepower = '?'
horsepower=auto_mpg.loc[auto_mpg['horsepower'] == '?']
horsepower
# Kết quả: có 3 loại xe mà horsepower ='?'

mpg  cylinders  displacement horsepower  weight  acceleration  \
32   25.0          4          98.0          ?  2046.0          19.0   
126  21.0          6         200.0          ?  2875.0          17.0   
330  40.9          4          85.0          ?  1835.0          17.3   
336  23.6          4         140.0          ?  2905.0          14.3   
354  34.5          4         100.0          ?  2320.0          15.8   
374  23.0          4         151.0          ?  3035.0          20.5   

     model_year  origin              car_name  
32           71       1            ford pinto  
126          74       1         ford maverick  
330          80       2  renault lecar deluxe  
336          80       1    ford mustang cobra  
354          81       2           renault 18i  
374          82       1        amc concord dl

In [17]:
# Lấy danh sách xe ford có horsepower = ?
ford_car=horsepower.loc[horsepower['car_name'].str.contains('ford')]
# Lấy horsepower của tất cả xe ford
ford_horsepower = auto_mpg.loc[(auto_mpg['car_name'].str.contains('ford', case= False)) & (auto_mpg['horsepower'] != '?')]
# Ép kiểu horsepower từ object sang float
ford_horsepower['horsepower'] = ford_horsepower['horsepower'].astype(float)
# Lấy horsepower trung bình của xe ford
avg_ford = ford_horsepower['horsepower'].mean()
# Thay thế các giá trị horsepower = ? của xe ford bằng giá trị trung bình này
indices = ford_car['horsepower'].index.values.tolist()
auto_mpg.loc[indices,'horsepower'] = np.around(avg_ford,2)
auto_mpg.head(33)

mpg  cylinders  displacement horsepower  weight  acceleration  \
0   18.0          8         307.0      130.0  3504.0          12.0   
1   15.0          8         350.0      165.0  3693.0          11.5   
2   18.0          8         318.0      150.0  3436.0          11.0   
3   16.0          8         304.0      150.0  3433.0          12.0   
4   17.0          8         302.0      140.0  3449.0          10.5   
5   15.0          8         429.0      198.0  4341.0          10.0   
6   14.0          8         454.0      220.0  4354.0           9.0   
7   14.0          8         440.0      215.0  4312.0           8.5   
8   14.0          8         455.0      225.0  4425.0          10.0   
9   15.0          8         390.0      190.0  3850.0           8.5   
10  15.0          8         383.0      170.0  3563.0          10.0   
11  14.0          8         340.0      160.0  3609.0           8.0   
12  15.0          8         400.0      150.0  3761.0           9.5   
13  14.0          8         455.0      225.0  3086.0          10.0   
14  24.0          4         113.0      95.00  2372.0          15.0   
15  22.0          6         198.0      95.00  2833.0          15.5   
16  18.0          6         199.0      97.00  2774.0          15.5   
17  21.0          6         200.0      85.00  2587.0          16.0   
18  27.0          4          97.0      88.00  2130.0          14.5   
19  26.0          4          97.0      46.00  1835.0          20.5   
20  25.0          4         110.0      87.00  2672.0          17.5   
21  24.0          4         107.0      90.00  2430.0          14.5   
22  25.0          4         104.0      95.00  2375.0          17.5   
23  26.0          4         121.0      113.0  2234.0          12.5   
24  21.0          6         199.0      90.00  2648.0          15.0   
25  10.0          8         360.0      215.0  4615.0          14.0   
26  10.0          8         307.0      200.0  4376.0          15.0   
27  11.0          8         318.0      210.0  4382.0          13.5   
28   9.0          8         304.0      193.0  4732.0          18.5   
29  27.0          4          97.0      88.00  2130.0          14.5   
30  28.0          4         140.0      90.00  2264.0          15.5   
31  25.0          4         113.0      95.00  2228.0          14.0   
32  25.0          4          98.0     112.23  2046.0          19.0   

    model_year  origin                      car_name  
0           70       1     chevrolet chevelle malibu  
1           70       1             buick skylark 320  
2           70       1            plymouth satellite  
3           70       1                 amc rebel sst  
4           70       1                   ford torino  
5           70       1              ford galaxie 500  
6           70       1              chevrolet impala  
7           70       1             plymouth fury iii  
8           70       1              pontiac catalina  
9           70       1            amc ambassador dpl  
10          70       1           dodge challenger se  
11          70       1            plymouth 'cuda 340  
12          70       1         chevrolet monte carlo  
13          70       1       buick estate wagon (sw)  
14          70       3         toyota corona mark ii  
15          70       1               plymouth duster  
16          70       1                    amc hornet  
17          70       1                 ford maverick  
18          70       3                  datsun pl510  
19          70       2  volkswagen 1131 deluxe sedan  
20          70       2                   peugeot 504  
21          70       2                   audi 100 ls  
22          70       2                      saab 99e  
23          70       2                      bmw 2002  
24          70       1                   amc gremlin  
25          70       1                     ford f250  
26          70       1                     chevy c20  
27          70       1                    dodge d200  
28          70       1       

In [18]:
# Lấy danh sách xe renault có horsepower = ?
renault_car=horsepower.loc[horsepower['car_name'].str.contains('renault')]
# Lấy horsepower của tất cả xe renault
renault_horsepower = auto_mpg.loc[(auto_mpg['car_name'].str.contains('renault', case= False)) & (auto_mpg['horsepower'] != '?')]
# Ép kiểu horsepower từ object sang float
renault_horsepower['horsepower'] = renault_horsepower['horsepower'].astype(float)
# Lấy horsepower trung bình của xe renault
avg_renault = renault_horsepower['horsepower'].mean()
# Thay thế các giá trị horsepower = ? của xe renault bằng giá trị trung bình này
indices = renault_car['horsepower'].index.values.tolist()
auto_mpg.loc[indices,'horsepower'] = np.around(avg_renault,2)
auto_mpg.head(331)

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0      130.0  3504.0          12.0   
1    15.0          8         350.0      165.0  3693.0          11.5   
2    18.0          8         318.0      150.0  3436.0          11.0   
3    16.0          8         304.0      150.0  3433.0          12.0   
4    17.0          8         302.0      140.0  3449.0          10.5   
..    ...        ...           ...        ...     ...           ...   
326  43.4          4          90.0      48.00  2335.0          23.7   
327  36.4          5         121.0      67.00  2950.0          19.9   
328  30.0          4         146.0      67.00  3250.0          21.8   
329  44.6          4          91.0      67.00  1850.0          13.8   
330  40.9          4          85.0       70.0  1835.0          17.3   

     model_year  origin                   car_name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
326          80       2         vw dasher (diesel)  
327          80       2        audi 5000s (diesel)  
328          80       2         mercedes-benz 240d  
329          80       3        honda civic 1500 gl  
330          80       2       renault lecar deluxe  

[331 rows x 9 columns]

In [19]:
# Lấy danh sách xe amc có horsepower = ?
amc_car=horsepower.loc[horsepower['car_name'].str.contains('amc')]
# Lấy horsepower của tất cả xe amc
amc_horsepower = auto_mpg.loc[(auto_mpg['car_name'].str.contains('amc', case= False)) & (auto_mpg['horsepower'] != '?')]
# Ép kiểu horsepower từ object sang float
amc_horsepower['horsepower'] = amc_horsepower['horsepower'].astype(float)
# Lấy horsepower trung bình của xe amc
avg_amc = amc_horsepower['horsepower'].mean()
# Thay thế các giá trị horsepower = ? của xe amc bằng giá trị trung bình này
indices = amc_car['horsepower'].index.values.tolist()
auto_mpg.loc[indices,'horsepower'] = np.around(avg_amc,2)
auto_mpg.head(375)

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0      130.0  3504.0          12.0   
1    15.0          8         350.0      165.0  3693.0          11.5   
2    18.0          8         318.0      150.0  3436.0          11.0   
3    16.0          8         304.0      150.0  3433.0          12.0   
4    17.0          8         302.0      140.0  3449.0          10.5   
..    ...        ...           ...        ...     ...           ...   
370  31.0          4         112.0      85.00  2575.0          16.2   
371  29.0          4         135.0      84.00  2525.0          16.0   
372  27.0          4         151.0      90.00  2735.0          18.0   
373  24.0          4         140.0      92.00  2865.0          16.4   
374  23.0          4         151.0      114.7  3035.0          20.5   

     model_year  origin                    car_name  
0            70       1   chevrolet chevelle malibu  
1            70       1           buick skylark 320  
2            70       1          plymouth satellite  
3            70       1               amc rebel sst  
4            70       1                 ford torino  
..          ...     ...                         ...  
370          82       1  pontiac j2000 se hatchback  
371          82       1              dodge aries se  
372          82       1             pontiac phoenix  
373          82       1        ford fairmont futura  
374          82       1              amc concord dl  

[375 rows x 9 columns]

In [20]:
#Kiểm tra lại
auto_mpg.isin(['?']).any()

mpg             False
cylinders       False
displacement    False
horsepower      False
weight          False
acceleration    False
model_year      False
origin          False
car_name        False
dtype: bool

In [21]:
#5. Kiểm tra có bao nhiêu ô NA
auto_mpg.isna().sum().sum()

0

In [22]:
# Kiểm tra bao nhiêu dòng có chứa NA
auto_mpg.isna().sum(axis=1).sum()

0

In [23]:
# Kiểm tra bao nhiêu cột có chứa NA
auto_mpg.isna().sum(axis=0).sum()

0

In [24]:
#6. Tìm chiến lược xử lý NA phù hợp (xóa các dòng chứa NA hay xóa các cột chứa NA hay điền giá trị cho NA với các chiến lược khác nhau)
# Trả lời: Không có giá trị NA nên chiến lược thay thế giá trị '?' ở cột horsepower là 
# thay thế bằng horsepower trung bình của nhãn hiệu xe đó, đã được trình bày ở trên

In [25]:
#7. Trích ra các dòng dữ liệu cho xe audi (cột car name)
audi= auto_mpg.loc[(auto_mpg['car_name'].str.contains('audi', case=False))]
audi

mpg  cylinders  displacement horsepower  weight  acceleration  \
21   24.0          4         107.0      90.00  2430.0          14.5   
119  20.0          4         114.0      91.00  2582.0          14.0   
141  29.0          4          98.0      83.00  2219.0          16.5   
177  23.0          4         115.0      95.00  2694.0          15.0   
274  20.3          5         131.0      103.0  2830.0          15.9   
317  34.3          4          97.0      78.00  2188.0          15.8   
327  36.4          5         121.0      67.00  2950.0          19.9   

     model_year  origin             car_name  
21           70       2          audi 100 ls  
119          73       2           audi 100ls  
141          74       2             audi fox  
177          75       2           audi 100ls  
274          78       2            audi 5000  
317          80       2            audi 4000  
327          80       2  audi 5000s (diesel)

In [26]:
#8. Tính trung bình mpg các xe audi đã trích ở trên
audi['mpg'].mean()

26.714285714285715

In [27]:
#9. Tương tự cho các xe ford có model year trước năm 1979
ford= auto_mpg.loc[(auto_mpg['car_name'].str.contains('ford', case= False)) & (auto_mpg['model_year'] < 79)]
ford['mpg'].mean()

18.2948717948718

## Câu 4 (1 đ)

Từ bảng dữ liệu `auto_mpg` đã xử lý NA ở trên và loại bỏ cột car name

1. Gom nhóm dữ liệu theo cylinders và tính trung bình mpg, nhận xét

1. Tương tự trên nhưng gom nhóm dữ liệu lần lượt theo model year, origin

1. Tương tự trên nhưng gom nhóm dữ liệu theo đồng thời cylinders và origin

1. Tương tự trên nhưng gom nhóm dữ liệu theo đồng thời model year và origin

1. Tương tự trên nhưng gom nhóm dữ liệu theo đồng thời cylinders và model year

1. Tương tự trên nhưng gom nhóm dữ liệu theo đồng thời cylinders, model year và origin

In [28]:
auto_mpg.drop(['car_name'], axis=1)

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0      130.0  3504.0          12.0   
1    15.0          8         350.0      165.0  3693.0          11.5   
2    18.0          8         318.0      150.0  3436.0          11.0   
3    16.0          8         304.0      150.0  3433.0          12.0   
4    17.0          8         302.0      140.0  3449.0          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0      86.00  2790.0          15.6   
394  44.0          4          97.0      52.00  2130.0          24.6   
395  32.0          4         135.0      84.00  2295.0          11.6   
396  28.0          4         120.0      79.00  2625.0          18.6   
397  31.0          4         119.0      82.00  2720.0          19.4   

     model_year  origin  
0            70       1  
1            70       1  
2            70       1  
3            70       1  
4            70       1  
..          ...     ...  
393          82       1  
394          82       2  
395          82       1  
396          82       1  
397          82       1  

[398 rows x 8 columns]

In [29]:
#1. Gom nhóm dữ liệu theo cylinders và tính trung bình mpg, nhận xét
auto_mpg.groupby('cylinders')['mpg'].mean()
#Nhân xét: độ trung bình tiêu hao nhiên liệu mpg (miles per gallon) tỷ lệ nghịch với số lượng xi-lanh (cylinders). Ngoại trừ xe có 3 xi-lanh độ tiêu hao nhiên liệu chỉ nhỉnh hơn 6 xi-lanh môt chút.
# Nhưng mpg trung bình của 4 xi-lanh lại nhiều gấp đôi của 8 xi lanh

cylinders
3    20.550000
4    29.286765
5    27.366667
6    19.985714
8    14.963107
Name: mpg, dtype: float64

In [30]:
#2 Tương tự trên nhưng gom nhóm dữ liệu lần lượt theo model year, origin
auto_mpg.groupby('model_year')['mpg'].mean().to_frame()


mpg
model_year           
70          17.689655
71          21.250000
72          18.714286
73          17.100000
74          22.703704
75          20.266667
76          21.573529
77          23.375000
78          24.061111
79          25.093103
80          33.696552
81          30.334483
82          31.709677

In [31]:
auto_mpg.groupby('origin')['mpg'].mean().to_frame()

mpg
origin           
1       20.083534
2       27.891429
3       30.450633

In [32]:
#3. Tương tự trên nhưng gom nhóm dữ liệu theo đồng thời cylinders và origin
auto_mpg.groupby(['cylinders','origin'])['mpg'].mean().to_frame()

mpg
cylinders origin           
3         3       20.550000
4         1       27.840278
          2       28.411111
          3       31.595652
5         2       27.366667
6         1       19.663514
          2       20.100000
          3       23.883333
8         1       14.963107

In [33]:
#4. Tương tự trên nhưng gom nhóm dữ liệu theo đồng thời model year và origin
auto_mpg.groupby(['model_year','origin'])['mpg'].mean().to_frame()

mpg
model_year origin           
70         1       15.272727
           2       25.200000
           3       25.500000
71         1       18.100000
           2       28.750000
           3       29.500000
72         1       16.277778
           2       22.000000
           3       24.200000
73         1       15.034483
           2       24.000000
           3       20.000000
74         1       18.333333
           2       27.000000
           3       29.333333
75         1       17.550000
           2       24.500000
           3       27.500000
76         1       19.431818
           2       24.250000
           3       28.000000
77         1       20.722222
           2       29.250000
           3       27.416667
78         1       21.772727
           2       24.950000
           3       29.687500
79         1       23.478261
           2       30.450000
           3       32.950000
80         1       25.914286
           2       37.288889
           3       35.400000
81         1       27.530769
           2       31.575000
           3       32.958333
82         1       29.450000
           2       40.000000
           3       34.888889

In [34]:
#5 Tương tự trên nhưng gom nhóm dữ liệu theo đồng thời cylinders và model year
auto_mpg.groupby(['cylinders','model_year'])['mpg'].mean().to_frame()

mpg
cylinders model_year           
3         72          19.000000
          73          18.000000
          77          21.500000
          80          23.700000
4         70          25.285714
          71          27.461538
          72          23.428571
          73          22.727273
          74          27.800000
          75          25.250000
          76          26.766667
          77          29.107143
          78          29.576471
          79          31.525000
          80          34.612000
          81          32.814286
          82          32.071429
5         78          20.300000
          79          25.400000
          80          36.400000
6         70          20.500000
          71          18.000000
          73          19.000000
          74          17.857143
          75          17.583333
          76          20.000000
          77          19.500000
          78          19.066667
          79          22.950000
          80          25.900000
          81          23.428571
          82          28.333333
8         70          14.111111
          71          13.428571
          72          13.615385
          73          13.200000
          74          14.200000
          75          15.666667
          76          14.666667
          77          16.000000
          78          19.050000
          79          18.630000
          81          26.600000

In [35]:
#6. Tương tự trên nhưng gom nhóm dữ liệu theo đồng thời cylinders, model year và origin
auto_mpg.groupby(['cylinders','model_year','origin'])['mpg'].mean().to_frame()

mpg
cylinders model_year origin           
3         72         3       19.000000
          73         3       18.000000
          77         3       21.500000
          80         3       23.700000
4         70         2       25.200000
...                                ...
8         76         1       14.666667
          77         1       16.000000
          78         1       19.050000
          79         1       18.630000
          81         1       26.600000

[76 rows x 1 columns]

## Câu 5 (5 và 6 và 7: 1 đ)

Tạo bảng dữ liệu SUPPLIER cho biết thông tin các hãng cung ứng sản phẩm như sau:

S# | NAME   | STATUS |	CITY
---|--------|--------|-------
S1 | Smith	| 20     | London
S2 | Jones  | 10     | Paris
S3 | Blacke | 30     | Paris

Trong đó:
  - S# là mã nhà cung ứng
  - NAME là tên nhà cung ứng
  - STATUS cho biết qui mô nhà cung ứng
  - CITY cho biết thành phố đặt trụ sở

In [36]:
# Tạo bảng supplier
supplier = pd.DataFrame({'S_ID': [f'S{i}' for i in range(1,4)], 'NAME': ['Smith','Jones','Blacke'], 'STATUS': [20,10,30], 'CITY': ['London','Paris','Paris']})
supplier


S_ID    NAME  STATUS    CITY
0   S1   Smith      20  London
1   S2   Jones      10   Paris
2   S3  Blacke      30   Paris

## Câu 6

Tạo bảng dữ liệu PRODUCT cho biết thông tin các sản phẩm như sau:

P# | NAME   | COLOR | WEIGHT | CITY
---|--------|-------|--------|-----
P1 | Nut	| Red   | 12     | London
P2 | Bolt   | Green | 17     | Paris
P3 | Screw  | Blue  | 17     | Rom
P4 | Screw  | Red   | 14     | London

Trong đó:
  - P# là mã sản phẩm
  - NAME là tên sản phẩm
  - COLOR là màu sản phẩm
  - WEIGHT cho biết trọng lượng sản phẩm
  - CITY cho biết nơi bán sản phẩm

In [37]:
#Tạo bảng product
product = pd.DataFrame({'P_ID': [f'P{i}' for i in range(1,5)], 'NAME': ['Nut','Bolt','Screw','Screw'],
                        'COLOR': ['Red','Green','Blue','Red'], 'WEIGHT': [12,17,17,14],'CITY':['London','Paris','Rom','London']})
product

P_ID   NAME  COLOR  WEIGHT    CITY
0   P1    Nut    Red      12  London
1   P2   Bolt  Green      17   Paris
2   P3  Screw   Blue      17     Rom
3   P4  Screw    Red      14  London

## Câu 7

Tạo bảng dữ liệu SUPPLIES cho biết thông tin các cung ứng như sau:

S# | P# | QTY
---|----|-----
S1 | P1	| 300
S1 | P2 | 200
S1 | P3 | 400
S2 | P1 | 300
S2 | P2 | 400
S3 | P2 | 200

Trong đó:
  - S# là mã nhà cung ứng
  - P# là mã sản phẩm
  - QTY là số lượng sản phẩm được cung ứng

In [38]:
#Tạo bảng supplies
supplies = pd.DataFrame({'S_ID': ['S1','S1','S1','S2','S2','S3'], 'P_ID': ['P1','P2','P3','P1','P2','P2'],
                        'QTY': [300,200,400,300,400,200]})
supplies

S_ID P_ID  QTY
0   S1   P1  300
1   S1   P2  200
2   S1   P3  400
3   S2   P1  300
4   S2   P2  400
5   S3   P2  200

## Câu 8 (2.5 đ)

Từ 3 bảng trên, thực hiện các truy vấn dữ liệu sau (có thể viết thêm các hàm phụ nếu cần):

1.	Đưa ra danh sách các hãng cung ứng có trụ sở (CITY) ở Paris.

1.	Đưa ra tên (NAME) của các sản phẩm có trọng lượng (WEIGHT) lớn hơn 15 và có màu (COLOR) xanh (Green).

1.	Đưa ra S# của hãng có STATUS lớn nhất.

1.	Đưa ra S# của các hãng cung ứng cả hai mặt hàng P1 và P2.

1.	Đưa ra S# của các hãng cung ứng mặt hàng Nut hoặc Bolt.

1.	Đưa ra S# của các hãng cung ứng ít nhất một mặt hàng màu đỏ.

1.	Đưa ra SNAME của các hãng cung ứng ít nhất hai mặt hàng.

1.	Đưa ra S# của các hãng cung ứng tất cả các mặt hàng.

In [39]:
#1 Đưa ra danh sách các hãng cung ứng có trụ sở (CITY) ở Paris.
supplier_idx = supplier.drop("S_ID", axis=1)
supplier_idx.index = supplier.S_ID

supplies_idx = supplies.drop("S_ID", axis=1)
supplies_idx.index = supplies.S_ID

result1 = supplier_idx.loc[supplier_idx['CITY']=='Paris']
result1.drop(['STATUS'], axis=1)

NAME   CITY
S_ID               
S2     Jones  Paris
S3    Blacke  Paris

In [40]:
#2 Đưa ra tên (NAME) của các sản phẩm có trọng lượng (WEIGHT) lớn hơn 15 và có màu (COLOR) xanh (Green).
result2= product.loc[(product['WEIGHT'] > 15) & (product['COLOR']== 'Green')]
result2.drop(['CITY'], axis=1)


P_ID  NAME  COLOR  WEIGHT
1   P2  Bolt  Green      17

In [41]:
#3 Đưa ra S# của hãng có STATUS lớn nhất.
result3 = supplier[supplier['STATUS'] == supplier['STATUS'].max()]
result3.drop(['CITY'], axis=1)

S_ID    NAME  STATUS
2   S3  Blacke      30

In [42]:
#4. Đưa ra S# của các hãng cung ứng cả hai mặt hàng P1 và P2.
result4= supplies.loc[(supplies['P_ID'] == 'P1') | (supplies['P_ID'] == 'P2' )]
result4.drop(['QTY'], axis=1)

S_ID P_ID
0   S1   P1
1   S1   P2
3   S2   P1
4   S2   P2
5   S3   P2

In [43]:
# 5. Đưa ra S# của các hãng cung ứng mặt hàng Nut hoặc Bolt.
product_idx = product.drop("P_ID", axis=1)
product_idx.index = product.P_ID

a = product.loc[(product['NAME'] == 'Nut') | (product['NAME'] == 'Bolt' )]
result5 = supplies.merge(a, how='inner', on='P_ID').drop(['QTY','COLOR','WEIGHT','CITY'], axis=1)
result5


S_ID P_ID  NAME
0   S1   P1   Nut
1   S2   P1   Nut
2   S1   P2  Bolt
3   S2   P2  Bolt
4   S3   P2  Bolt

In [44]:

#6. Đưa ra S# của các hãng cung ứng ít nhất một mặt hàng màu đỏ.
red = product.loc[product['COLOR'] == 'Red']
result6 = supplies.merge(red, how='inner', on='P_ID').drop(['QTY','NAME','WEIGHT','CITY'], axis=1)
result6

S_ID P_ID COLOR
0   S1   P1   Red
1   S2   P1   Red

In [45]:
#7 Đưa ra S NAME của các hãng cung ứng ít nhất hai mặt hàng.
atleast2 = supplies['P_ID'].value_counts(ascending=True).loc[lambda x : x >= 2].to_frame()
atleast2_supplies= pd.merge(supplies, atleast2, how='inner', on='P_ID')
atleast2_supplies
result7 = pd.merge(supplier, atleast2_supplies, how='inner', on='S_ID')
result7.drop(['QTY', 'count','STATUS','CITY'], axis=1)

S_ID    NAME P_ID
0   S1   Smith   P1
1   S1   Smith   P2
2   S2   Jones   P1
3   S2   Jones   P2
4   S3  Blacke   P2

In [46]:
#8. Đưa ra S# của các hãng cung ứng tất cả các mặt hàng.
result8 = pd.merge(supplier, supplies, how='inner', on='S_ID').drop(['NAME','STATUS','CITY','QTY'], axis=1)
result8.groupby(['S_ID']).apply(lambda a: a[:])
#result8.groupby(['S_ID']).apply(display)

S_ID P_ID
S_ID            
S1   0   S1   P1
     1   S1   P2
     2   S1   P3
S2   3   S2   P1
     4   S2   P2
S3   5   S3   P2